#!/usr/bin/env python3

import argparse
import math
import sys
from typing import List

import sinter


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--stats",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--cores",
        type=int,
        default=96,
    )
    args = parser.parse_args()

    stats: List[sinter.TaskStats] = sinter.stats_from_csv_files(args.stats)

    total_core_seconds = sum(st.seconds for st in stats)

    print(f"Total Core-Seconds: {total_core_seconds}")
    print(f"Total Core-Hours:   {total_core_seconds / 60 / 60}")
    print(f"Total Core-Days:    {total_core_seconds / 60 / 60 / 24}")
    print(f"Total Core-Years:   {total_core_seconds / 60 / 60 / 24 / 365}")
    print()
    print(f"Using Cores = {args.cores}")
    print(f"Total Seconds:      {total_core_seconds / args.cores}")
    print(f"Total Hours:        {total_core_seconds / 60 / 60 / args.cores}")
    print(f"Total Days:         {total_core_seconds / 60 / 60 / 24 / args.cores}")


if __name__ == '__main__':
    main()
